### ISSUE TITLE
Presentation Mode

### ISSUE THREAD

**Issue by dennykorsukewitz** [karldaeubel/PenAndPaperFloorplanner#11]
I would like to see a presentation mode.

## presentation mode
- Presentation without nodes (Room-Mode) and pivots (Furniture-Mode)
- Wall length should then be actively displayed (from node to node) 

![Node](https://github.com/karldaeubel/PenAndPaperFloorplanner/assets/3249687/c1847742-51c0-4280-85f6-eb95ace52010)

![Point](https://github.com/karldaeubel/PenAndPaperFloorplanner/assets/3249687/da1c7e4d-cc6b-482b-90ac-8738aaded63a)

In general, there should be a checkbox with which you can activate the wall length constantly.

![Bildschirmfoto 2023-08-09 um 08 46 34](https://github.com/karldaeubel/PenAndPaperFloorplanner/assets/3249687/ccb28312-10f7-48b4-8de9-edae753f04af)

**Comment by dennykorsukewitz** [comment]
🚀

**Comment by karldaeubel** [comment]
Thanks for the Issue, it's a nice addition! :smiley:
