### ISSUE TITLE
Browser compatibility - Alert Limit

### ISSUE THREAD

**Issue by dennykorsukewitz** [karldaeubel/PenAndPaperFloorplanner#20]
Firefox: ✅ 
Chrome: 🚫  Version 116.0.5845.110 (Offizieller Build) (arm64)

![Bildschirmfoto 2023-08-29 um 11 26 03](https://github.com/karldaeubel/PenAndPaperFloorplanner/assets/3249687/f0457e12-069c-4d77-bf96-7d8dad875f93)

Safari: 🚫 Version 16.6 (18615.3.12.11.2)

![Bildschirmfoto 2023-08-29 um 11 29 12](https://github.com/karldaeubel/PenAndPaperFloorplanner/assets/3249687/0a690c4e-5e70-41bf-9f81-071e5995359c)

**Comment by karldaeubel** [comment]
Noticed it before too on a Chrome based browser. It's a good opportunity to improve the help text while I'm at it.

Thanks.
